name: Build and Test - API Gateway

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Build and test
        run: |
          npm ci
          npm run lint
          npm run build
          npm test
          
      - name: Build Docker image
        run: docker build -t api-gateway:${{ github.ref_name }} .
        
      - name: Test Docker container
        run: |
          echo "Testing Docker image: api-gateway:${{ github.ref_name }}"
          
          # Start container
          docker run -d --name test-container -p 3000:3000 \
            -e NODE_ENV=test \
            -e PORT=3000 \
            api-gateway:${{ github.ref_name }}
          
          # Wait for startup
          sleep 10
          
          # Test health endpoint
          curl -f http://localhost:3000/health || exit 1
          
          # Cleanup
          docker stop test-container
          docker rm test-container
          
          echo "Docker image test completed successfully!"
